### ISSUE TITLE
"funcion" in blockly_compressed.js

### ISSUE THREAD

**Issue by i8beef** [mo4islona/node-blockly#1]
In the version that I pull down from NPM, in the blockly_compressed.js file there is a mispelled "function" (spelled as "funcion") that breaks stuff. Any chance of a release to fix that?

**Comment by mo4islona** [comment]
I've updated blockly to latest version. This typo has been fixed.
Please try 1.0.2

**Comment by i8beef** [comment]
Well it fixed that issue and opened another one :-)

I'm getting ReferenceError: Invalid left-hand side in assignment on line 288.

P.S.: Thanks for the quick response time!

**Comment by i8beef** [comment]
Seems like line 288 got duplicated twice or something along those lines.

**Comment by mo4islona** [comment]
Thx for response!
Try 1.0.3

**Comment by i8beef** [comment]
Looks good! Thanks!
