### ISSUE TITLE
Error: Blockly.Extensions is undefined

### ISSUE THREAD

**Issue by Razaik25** [mo4islona/node-blockly#11]
I'm trying to use Blockly.Extensions with this library to do validations in the browser. But I get the error that Blockly.Extensions is undefined. Is there support for Blocky.Extensions in this library?

**Comment by mo4islona** [comment]
Hi there! Sorry for the delay. Are you using special browser build in a browser?

Latest version node-blockly
```js
const Blockly = require('node-blockly/browser');
const keys = Object.keys(Blockly.Extensions)
console.log(keys)
```


```json
["ALL_", "MUTATOR_PROPERTIES_", "register", "registerMixin", "registerMutator", "apply", "checkHasFunction_", "checkNoMutatorProperties_", "checkMutatorDialog_", "checkBlockHasMutatorProperties_", "getMutatorProperties_", "mutatorPropertiesMatch_", "buildTooltipForDropdown", "checkDropdownOptionsInTable_", "buildTooltipWithFieldValue", "extensionParentTooltip_"]
```

**Comment by Razaik25** [comment]
Hi, 
This issue was resolved with the release of version. 1.0.17. I will close the issue.
Thanks!!
