### ISSUE TITLE
Calling Blockly.setLocale has uncaught error.

### ISSUE THREAD

**Issue by NAllred91** [mo4islona/node-blockly#14]
For some reason, when I call Blockly.setLocale() I get an uncaught type error, `Uncaught TypeError: _.extend(...) is not a function`

This is in browser.js line 14.  I'm not sure what causes this to happen..

**Comment by NAllred91** [comment]
Rolling back to node-blockly 1.0.21 resolves this issue.

**Comment by mo4islona** [comment]
Still reproduce in 1.0.24?

**Comment by NAllred91** [comment]
This is not reproducible in 1.0.24.  Although 1.0.24 has an issue when you scroll up in the flyout, but that is probably an issue with blockly itself at the moment.

**Comment by NAllred91** [comment]
https://github.com/google/blockly/issues/1220  Yep, I'll probably just stay at 1.0.21 until that issue is resolved by the blockly team.

**Comment by NAllred91** [comment]
@mo4islona I got a fix for the scroll issue merged into blockly.  Do you mind updating the version of blockly?

**Comment by mo4islona** [comment]
Yeah, sure. Please check the latest version 1.0.28
