### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Immortalin** [mo4islona/node-blockly#15]
I am getting an error with the following code:

```xml
<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables></variables>
  <block type="controls_repeat_ext" id="(BFo|WQ,-6A?iUwjWMq*" x="238" y="63">
    <value name="TIMES">
      <shadow type="math_number" id="QU(s4?wLG]]%mQZ:pPQP">
        <field name="NUM">10</field>
      </shadow>
    </value>
  </block>
</xml>
```

Most of the XML generated by [this](https://blockly-demo.appspot.com/static/demos/code/index.html) doesn't seem to work with `node-blockly` (tested the XML against the in-browser [generator](https://blockly-demo.appspot.com/static/demos/headless/index.html), XML is valid).

**Comment by mo4islona** [comment]
Seems, Blockly uses DOM4 API props like `Element.children`. But nodejs `xmldom` lib doesn`t support it.
Will try to fix that.

Thx!

**Comment by Immortalin** [comment]
@mo4islona maybe use http://webreflection.github.io/dom4/ or jsdom?

**Comment by Immortalin** [comment]
Or for even faster speed: https://github.com/libxmljs/libxmljs

**Comment by Immortalin** [comment]
@mo4islona any luck?
