### ISSUE TITLE
xmlshim related issue

### ISSUE THREAD

**Issue by m7mdbadawy** [mo4islona/node-blockly#17]
From the commit history I can see that you have moved to `xmlshim` that will cause a problem in build for people who are behind an http proxy

`xmlshim` depends on pulling `libxmljs`  from `git://github.com/znerol/libxmljs.git#xmlwriter-0.17.1` and this  url doesn't work behind an http proxy

I had the following error

`Command failed: /usr/bin/git clone --depth=1 -q -b xmlwriter-0.18.0 git://github.com/znerol/libxmljs.git /home/jenkins/.npm/_cacache/tmp/git-clone-bd5b74dd`

This broke my build unfortunately and probably will break other people's build who uses http proxy

**Comment by NAllred91** [comment]
I'm having xmlshim related issues as well, even when I am able to build.

**Comment by mo4islona** [comment]
Do you use node-blockly in a browser? 

Xmlshim is needed only for node.js. I'll try to find another solution to parse xml

**Comment by m7mdbadawy** [comment]
@mo4islona I use it for both browser and backend

**Comment by dustismo** [comment]
This issue has also broken our build, we cannot pull in non npm dependencies.  We've had to downgrade node-blockly because of this.  We tried to fix this on xmlshim, see @znerol's response on https://github.com/znerol/node-xmlshim/pull/6

**Comment by znerol** [comment]
Yeah, this situation is really unfortunate. I've published 0.2.3 which explicitly specifies git+https as the protocol for the libxmljs dependency. This should at least help with the http-proxy problem.
