### ISSUE TITLE
How to import custom blocks and generate code?

### ISSUE THREAD

**Issue by Simonefardella** [mo4islona/node-blockly#26]
Hi, i've tried to import custom blocks using the "Import" directive in Node (I'm not a Node.js guru...), then load my XML and finally i've tried to generate my Python Code, but i'm receiving this error:

```
> Blockly.Python.workspaceToCode(workspace);
TypeError: Cannot read property 'call' of undefined
    at module.exports.Blockly.Generator.blockToCode

```
Do you know why? it's possible to import custom blocks definition and imports on your Node Module?

Thanks.

**Comment by Simonefardella** [comment]
Solved by importing the stubs and custom code blocks via the require statement

**Comment by LarryKlugerDS** [comment]
Hi @Simonefardella ,

Can you provide an example of the code you used?

Thanks,
Larry
