### ISSUE TITLE
static files from server

### ISSUE THREAD

**Issue by zfan40** [mo4islona/node-blockly#27]
I noticed some references from https://blockly-demo.appspot.com/static/media/
including files such as click.mp3, disconnect.wav, delete.mp3, sprites.png

I am wondering if these can be transformed to base64, so that every project could parse them...
Yes, some corner of this world cannot connect to blockly-demo.appspot.com by default...
Thanks

**Comment by mo4islona** [comment]
You can configure media URL and load audio from local server. Check `media` property in `Blockly.inject` method https://developers.google.com/blockly/guides/get-started/web
