### ISSUE TITLE
Does not compile on Node 12

### ISSUE THREAD

**Issue by Chris927** [mo4islona/node-blockly#35]
node-blockly does not compile on node v12.10.0, it errors compiling `libxmljs`.

@mo4islona I see you've created [an issue upstream](https://github.com/znerol/node-xmlshim/issues/13) upstream already.

What is the status? For our current (new) experiments with blockly I've downgraded to node 10, but that's just for a short while.

**Comment by Chris927** [comment]
@mo4islona I may be able to help fix / overcome this, but I'm not proficient in gulp (any more). Please let me know.

**Comment by mo4islona** [comment]
Done
