### ISSUE TITLE
Latest blockly version: goog is not defined

### ISSUE THREAD

**Issue by greyivy** [mo4islona/node-blockly#36]
When trying to use this package with the latest version of blockly, I get the following error (via test and server use):

`ReferenceError: goog is not defined`

**Comment by greyivy** [comment]
This seems to have fixed it, although I'm not sure if it has the potential to break anything:
https://github.com/greyivy/node-blockly/commit/ad63265fd5723f2ecefbe5c26da255264490c3f2

**Comment by mo4islona** [comment]
Could you provide code that produce such error?

**Comment by greyivy** [comment]
The included test (via npm test) should produce it if Blockly is upgraded.

**Comment by mo4islona** [comment]
Thanks! It works fine.
