### ISSUE TITLE
for help！--blockly's user block program data pass

### ISSUE THREAD

**Issue by liudxhit** [mo4islona/node-blockly#37]
Looking forward to your reply！
I want to build a local application with blockly and three.js on the web page, and pass the return value of blockly's user block program to define/require state management module, so as to realize real-time data interaction。How do you pass data in eval?

**Comment by liudxhit** [comment]
Hello, can this node-blockly project be used in the browser client?

**Comment by mo4islona** [comment]
Yes, you can use it in a browser!

Demo - http://mo4islona.github.io/blockly/ 
Source of demo - https://github.com/mo4islona/mo4islona.github.io/blob/master/blockly/index.js
