### ISSUE TITLE
Update to Blockly Q2 2020?

### ISSUE THREAD

**Issue by luddilo** [mo4islona/node-blockly#42]
Hi! Anyone working on updating to the latest Blockly release (Q2 2020)? https://github.com/google/blockly/releases

**Comment by mo4islona** [comment]
I guess this project is deprecated because you can use https://www.npmjs.com/package/blockly in Node.js and browser environments directly for now.

**Comment by luddilo** [comment]
Ah, that makes sense. Thanks for your work @mo4islona!
