### ISSUE TITLE
how to use `Blockly.inject` with  node-blockly

### ISSUE THREAD

**Issue by wwj718** [mo4islona/node-blockly#5]
hi,

node-blockly is great, I like it 

how to use `Blockly.inject` with  node-blockly

**Comment by mo4islona** [comment]
Hi!

I've added an example how to use Webpack + Blockly.inject

Check out 
https://github.com/mo4islona/node-blockly/blob/master/test/browser/inject.html
https://github.com/mo4islona/node-blockly/blob/master/test/browser/inject.js

**Comment by mo4islona** [comment]
Install

Go to `test/browser`
`npm i`
`webpack`
Then open inject.html

**Comment by wwj718** [comment]
@mo4islona  Great!  thanks a lot

but I can't find media file. such as delete.mp3 , click.mp3  , handopen.cur

![image](https://cloud.githubusercontent.com/assets/3153878/20131650/c4867fb2-a699-11e6-8ada-cf74096bc0ee.png)

![image](https://cloud.githubusercontent.com/assets/3153878/20131686/0929fee6-a69a-11e6-85b1-c9bbd8b444d5.png)

**Comment by mo4islona** [comment]
Blockly loads media assets automatically

There is an a option `media` – path from page (or frame) to the Blockly media directory. Defaults to https://blockly-demo.appspot.com/static/media/.

You can change this path 

`var Blockly = require('node-blockly/browser')`
`var workspace = Blockly.inject('inject', {
      media: "http://yourpath-to-media-assets",
    });`

**Comment by wwj718** [comment]
Got it ！thanks！

**Comment by promethe42** [comment]
> Check out
> https://github.com/mo4islona/node-blockly/blob/master/test/browser/inject.html
> https://github.com/mo4islona/node-blockly/blob/master/test/browser/inject.js

I think those files are missing now.
Where can I find them?

**Comment by mo4islona** [comment]
@promethe42 https://github.com/mo4islona/mo4islona.github.io/blob/master/blockly/index.js
