### ISSUE TITLE
package.json dependencies

### ISSUE THREAD

**Issue by benjie** [mo4islona/node-blockly#9]
Hi @mo4islona,

I think we can move all the dependencies to `devDependencies` so this becomes a dependency free package (or just one dependency). We only seem to be using lodash for `_.extend` which can be easily emulated; the others only seem to be needed at build time. Before setting about doing this I wanted to ensure I wasn't missing something - is there a reason I've overlooked that we need the other dependencies for people who install via `npm`?

Cheers,

Benjie.

**Comment by mo4islona** [comment]
Hi!
Yeah, you are right. All dependencies except `lodash` are using for re-building Blockly source files. We should transfer these dependencies to `devDependencies`. Also we can drop `lodash`, if `_.extend` will be refactored using native functions

**Comment by mo4islona** [comment]
I've fixed `package.json` by https://github.com/mo4islona/node-blockly/commit/454aaac4b3c04cade064a55a1b556d64cccf432c

**Comment by benjie** [comment]
Awesome, nice one 👍
